# @package _global_
profile:
  name: full

training:
  rounds: 200
  batch_size: 128
  eval_interval: 1

client:
  num_clients: 5

server:

runtime:
  use_torch_distributed: false
  deterministic: true

tracking:
  tracker: csv
  wandb_enabled: false

